protected/modules/clients/models/Clients.php
<?php

/**
 * This is the model class for table "clients".
 *
 * The followings are the available columns in table 'clients':
 *
 * @property string $id
 * @property string $title
 * @property string $email_comment
 * @property string $contact_name1
 * @property string $contact_name2
 * @property string $contact_name3
 * @property integer $branch_id
 * @property string $career
 * @property string $website
 * @property integer $region_id
 * @property string $city_id
 * @property string $address
 * @property string $legal_address
 * @property string $inn
 * @property string $kpp
 * @property integer $user_id
 * @property string $contract_end_date
 * @property integer $is_duplication
 * @property string $comment
 * @property string $importance
 * @property string $next_contact
 * @property string $created Дата создания клиента
 * @property string $sended_bids список отправленных заявок
 * @property string $client_status Статус клиента
 * @property string $action_description Описание деятельности компании
 * @property string $payment_status Статус оплаты
 *
 * The followings are the available model relations:
 * @property ClientEmails[] $clientEmails
 * @property ClientPhones[] $clientPhones
 * @property ClientProtocol[] $clientProtocols
 * @property ClientSubscribeEmails[] $clientSubscribeEmails
 * @property Addresses $region
 * @property Addresses $city
 * @property Branches $branch
 * @property Users $user
 */
class Clients extends CActiveRecord
{
    /**
     * Email'ы по которым ищем клиентов
     *
     * @var string
     */
    public $searchedEmails;

    /**
     * Название года, по которому ищем клиента
     *
     * @var string
     */
    public $searchedCity;

    /**
     * Номер телефона, по которому ищем клиента
     *
     * @var string
     */
    public $searchedPhones;

    /**
     * Дата последней записи в протоколе, по которой ищем
     *
     * @var string
     */
    public $searchedLastProtocolRecordDate;

    /**
     * Тип связки поисковых полей
     *
     * @var string 'OR' или 'AND'
     */
    public $searchConditionType = 'AND';

    /**
     * Фильтр.
     * Диапазон даты последнего контакта
     */
    public $next_contact_from;
    public $next_contact_to;

    /**
     * Фильтр.
     * Контактное лицо
     */
    public $contact_name;

    /**
     * Фильтр.
     * Протокол
     */
    public $protocol;

    /**
     * Фильтр.
     * Диапазон даты окончания контракта
     */
    public $contract_end_date_from;
    public $contract_end_date_to;

    /**
     * Фильтр.
     * Диапазон даты создания клиента
     */
    public $created_from;
    public $created_to;

    /**
     * Фильтр.
     * Дата последней записи в протоколе.
     */
    public $protocol_last_date;
    public $protocol_last_date_from;
    public $protocol_last_date_to;

    /**
     * Активные рассылки.
     * Используется в фильтре для выбора клиентов, у которых есть активные (включенные) рассылки.
     */
    public $active_mailing = 2;

    /**
     * Returns the static model of the specified AR class.
     *
     * @param string $className active record class name.
     * @return Clients the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    /**
     *
     * @return string the associated database table name
     */
    public function tableName()
    {
        return 'clients';
    }

    /**
     *
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return [
            // common
            [
                'title',
                'required'
            ],
            ['client_status', 'required'],
            [
                'branch_id, user_id, is_duplication',
                'numerical',
                'integerOnly' => true
            ],
            ['region_id, city_id', 'length', 'max' => 36],
            [
                'id, next_contact, contract_end_date',
                'length',
                'max' => 10
            ],
            [
                'client_status, payment_status, importance, title, email_comment, contact_name1, contact_name2, contact_name3, career, website, address, legal_address',
                'length',
                'max' => 256
            ],
            [
                'inn, kpp',
                'length',
                'max' => 12
            ],
            [
                'searchConditionType',
                'in',
                'range' => [
                    'AND',
                    'OR'
                ]
            ],
            // quick_insert
            ['searchedEmails', 'safe', 'on' => 'quick_insert'],
            // search
            [
                'active_mailing, protocol_last_date, protocol_last_date_from, protocol_last_date_to, contract_end_date_from, contract_end_date_to, created_from, created_to, protocol, contact_name, next_contact_from, next_contact_to, searchedLastProtocolRecordDate, searchedPhones, searchedCity, searchedEmails, clientEmails, id, title, email_comment, contact_name1, contact_name2, contact_name3, branch_id, career, website, region_id, city_id, address, legal_address, inn, kpp, user_id, is_duplication, comment, action_description, importance, client_status, payment_status',
                'safe',
                'on' => 'search'
            ],
            // edit
            [
                'title, clientEmails',
                'required',
                'on' => 'edit'
            ],
            [
                'clientPhones',
                'filter',
                'filter' => [
                    $this,
                    'filterPhonesToString'
                ],
                'on' => 'edit'
            ],
            [
                'clientEmails',
                'filter',
                'filter' => [
                    $this,
                    'filterEmailsToString'
                ],
                'on' => 'edit'
            ],
            [
                'clientSubscribeEmails',
                'filter',
                'filter' => [
                    $this,
                    'filterEmailsToString'
                ],
                'on' => 'edit'
            ],
            [
                'clientProtocols',
                'filter',
                'filter' => [
                    $this,
                    'filterClientProtocols'
                ],
                'on' => 'edit'
            ],
            [
                'contract_end_date, next_contact',
                'filter',
                'filter' => [
                    $this,
                    'filterUnixtimestampToDate'
                ],
                'on' => 'edit'
            ],
            // form_error Оставляем поля связанных моделей в виде "как есть"
            [
                'clientPhones, clientEmails, clientSubscribeEmails, clientProtocols',
                'safe',
                'on' => 'form_error'
            ],
            // form_add
            [
                'title, clientEmails, region',
                'required',
                'on' => 'form_add'
            ],
            [
                'clientPhones',
                'filter',
                'filter' => [
                    $this,
                    'filterStringToArray'
                ],
                'on' => 'form_add'
            ],
            [
                'clientEmails',
                'filter',
                'filter' => [
                    $this,
                    'filterStringToArray'
                ],
                'on' => 'form_add'
            ],
            [
                'clientSubscribeEmails',
                'filter',
                'filter' => [
                    $this,
                    'filterStringToArray'
                ],
                'on' => 'form_add'
            ],
            [
                'contract_end_date, next_contact',
                'filter',
                'filter' => 'strtotime',
                'on' => 'form_add'
            ],
            /*[
                'next_contact',
                'filter',
                'filter' => [
                        $this,
                        'filterCorrectJsTimestamp'
                ],
                'on' => 'form_add'
            ],*/
            ['created, sended_bids, comment, action_description', 'safe']
        ];
    }

    public function filterCorrectJsTimestamp($value)
    {
        return strtotime(date('Y-m-d', intval($value)));
    }

    public function filterPhonesToString($value)
    {
        return $this->ArrayToString($value, 'phone');
    }

    public function filterEmailsToString($value)
    {
        return $this->ArrayToString($value, 'email');
    }

    /**
     * Конвертирует дату из формата unixtimestamp в строку по шаблону "Y-m-d"
     *
     * @param integer $value Дата в формате unixtimestamp
     * @return string
     */
    public function filterUnixtimestampToDate($value)
    {
        return date("Y-m-d", $value);
    }

    /**
     * Преобразуем массив со строковыми значениями в строку, в которой значания
     * перечислены через запятую
     *
     * @param array $value - массив со строковыми значениями
     * @return string
     */
    public function filterStringToArray($value)
    {
        $data = array_unique(explode(',', trim($value . ',')));
        return array_filter($data, 'trim');
    }

    /**
     * Преобразует массив моделей с строку, в которой через запятую перечислены
     * значения указанного поля каждой модели
     *
     * @param CModel[] $value массив моделей
     * @param string $fieldName название поля
     * @return string
     * @throws InvalidArgumentException
     */
    public function arrayToString($value, $fieldName)
    {
        if (!is_array($value)) {

protected/modules/clients/controllers/ClientsController.php
<?php

/**
 * Контроллер клиентов
 */
class ClientsController extends Controller
{

    /**
     * @return array action filters
     */
    public function filters()
    {
        return ['accessControl'];
    }

    public function accessRules()
    {
        return [
            ['allow',
                'roles' => ['manager'],
            ],
            ['deny', // deny all users
                'users' => ['*'],
            ],
        ];
    }

    /**
     * Карточка клиента
     */
    public function actionIndex()
    {
        $this->title = 'Клиенты';
        $clientSearchModel = new Clients('search');
        $clientSearchModel->unsetAttributes();
        if (!Yii::app()->user->checkAccess('admin')) {
            $clientSearchModel->user_id = Yii::app()->user->id;
        }

        // если нажали кнопку 'Найти'
        if (Yii::app()->request->getParam('button_search')) {
            $requestData = Yii::app()->request->getParam('Clients', []);
            $clientSearchModel->attributes = $requestData;
        } elseif (Yii::app()->request->getPost('button_add')) {
            // если нажали кнопку 'Добавить'
            $requestData = Yii::app()->request->getPost('Clients', []);
            $clientModel = new Clients('quick_insert');
            $clientModel->attributes = $requestData;
            $clientModel->user_id = Yii::app()->user->id;
            $clientModel->save();
        }

        $this->render('index', ['model' => $clientSearchModel]);
    }

    /**
     * Обновление модели клиентов
     * @return type
     */
    public function actionUpdate()
    {
        $this->title = 'Карточка клиента';
        $id = Yii::app()->request->getParam('id');
        $clientModel = $id !== null ? Clients::model()->findByPk($id) : new Clients();

        if (is_null($clientModel)) {
            throw new CHttpException(404, 'Модель не найдена');
        }

        if (Yii::app()->request->isPostRequest) {
            $postData = Yii::app()->request->getPost('Clients');
            if ($postData === null)
                throw new RuntimeException('Данные модели Clients отсутствуют в запросе.');

            $clientModelErrors = clone ($clientModel);
            $clientModelErrors->setScenario('form_error');
            $clientModelErrors->attributes = $postData;

            $clientModel->setScenario('form_add');
            $clientModel->attributes = $postData;

            if($clientModel->isNewRecord) {
                $clientModel->next_contact = time();
            }

            if (isset($postData['user_id']) && !Yii::app()->user->checkAccess('changeClientsManager') &&  !Users::isMyUser(Yii::app()->user->id, $postData['user_id'])) {
                throw new CHttpException(403, 'Не хватает прав на изменение менеджера.');
            }

            $clientModel->save();

            if ($clientModel->hasErrors()) {
                $clientModelErrors->addErrors($clientModel->errors);
                $this->render('update', ['model' => $clientModelErrors]);
                return;
            }

            Yii::app()->request->redirect('/clients/clients/update/' . $id);
        }

        if (!Yii::app()->user->checkAccess('editClients', ['user_id' => $clientModel->user_id]) &&
                !Users::isMyUser(Yii::app()->user->id, $clientModel->user_id)) {
            throw new CHttpException(403, 'Не хватает прав для редактирования карточки клиента.');
        }

        $this->render('update', ['model' => $clientModel]);
    }

    public function actionDelete()
    {
        $id = Yii::app()->request->getParam('id');

        if (is_null($id)) {
            throw new CHttpException('Не задан id', 500);
        }

        $model = Clients::model()->findByPk($id);

        if (is_null($model)) {
            throw new CHttpException(404, 'Модель не найдена.');
        }

        $model->delete();
        exit;
    }

    /**
     * Список регионов для поля с автозаполнением.
     *
     * @return json
     */
    public function actionGetRegions()
    {
        $regions = [];

        if (!empty($_GET['title'])) {
            $models = Addresses::findAllRegionsByTitle($_GET['title']);

            foreach ($models as $region) {
                $regions[] = [
                    'id' => $region->AOID,
                    'region_id' => $region->AOGUID,
                    'short_name' => $region->SHORTNAME,
                    'title' => $region->OFFNAME
                ];
            }
        }

        echo CJSON::encode($regions);

        Yii::app()->end();
    }

    /**
     * Список населенных пунктов для поля с автозаполнением.
     *
     * @return json
     */
    public function actionGetCities()
    {
        $cities = [];
        $models = Addresses::findAllCitiesByTitle(
                        !empty($_GET['region']) ? $_GET['region'] : '', !empty($_GET['title']) ? $_GET['title'] : ''
        );

        foreach ($models as $city) {
            $cities[] = [
                'id' => $city->AOID,
                'short_name' => $city->SHORTNAME,
                'title' => $city->OFFNAME,
                'region_id' => $city->region !== null ? $city->region->AOID : null,
                'region_short_name' => $city->region !== null ? $city->region->SHORTNAME : '',
                'region_title' => $city->region !== null ? $city->region->OFFNAME : '',
            ];
        }

        echo CJSON::encode($cities);

        Yii::app()->end();
    }

}

protected/modules/clients/views/clients/form/search.php
<?php
/* @var $form TbActiveForm */
/* @var $model Clients */
/* @var $this Controller */
?>
	<?php
	$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', [
		'id' => 'clients',
		'action' => $this->createUrl('clients/index'),
        'type' => 'horizontal',
        'htmlOptions' => ['class' => 'well'],
		/*'enableAjaxValidation' => true*/
	]);
?>
<div class="control-group">
    <div class="controls">
        <div class="row-fluid">
            <?= CHtml::button('Добавить клиента', ['name' => 'button_add', 'class' => 'btn btn-primary span3']);?>
        </div>
    </div>
</div>
<?
    echo $form->textFieldRow($model, 'title', ['class' => 'span9']);
    echo $form->textFieldRow($model, 'searchedEmails', ['class' => 'span9']);
    echo $form->textFieldRow($model, 'website', ['class' => 'span9']);
    echo $form->dropDownListRow($model, 'client_status', CMap::mergeArray(['' => "- любой -"],  Clients::getDropdownClientStatus(true)), ['class' => 'span9']);

?>
    <div class="control-group ">
        <?=$form->labelEx($model, 'city_id', ['class' => 'control-label'])?>
        <div class="controls">
            <?
            echo $form->hiddenField($model, 'region_id') . $form->hiddenField($model, 'city_id');
            $this->widget(
                'zii.widgets.jui.CJuiAutoComplete',
                [
                    'name' => 'city_title',
                    'value' => $model->city ? $model->city->OFFNAME . ' ' . $model->city->SHORTNAME : '',
                    'source' => 'js: function(request, response) {
            $.ajax({
            url: "/clients/clients/getCities/",
            dataType: "json",
            beforeSend: function() { $("#loading_cities").show(); },
            complete: function() { $("#loading_cities").hide(); },
            data: { region: "", title: request.term },
            success: function(data) {
            response(data
            ? $.map(data, function(item) {
            var title = item.title + " " + item.short_name,
            label = title + " (" + item.region_title + " " + item.region_short_name + ")";

            return { id: item.id, value: title, label: label, region_id: item.region_id }
            })
            : {}
            );
            }
            });
            }',
                    // при выборе города, вставляем и айдишник региона
                    'options' => [
                        'showAnim' => 'fold',
                        'select' => 'js: function(event, ui) {
            $("#' . get_class($model) . '_city_id").val(ui.item.id);
            $("#' . get_class($model) . '_region_id").val(ui.item.region_id);
            }',
                        'change' => 'js: function(event, ui) {
            if (!ui.item) {
            $("#' . get_class($model) . '_city_id").val("");
            $("#' . get_class($model) . '_region_id").val("");
            }
            }'
                    ],
                    'htmlOptions' => [
                        'class' => 'span9'
                        //'style' => 'width: 100%',
                    ],
                ]
            );
            ?><img id="loading_cities" style="display: none;" src="<?=Yii::app()->request->baseUrl; ?>/images/spinner.gif"/>
            <?echo $form->error($model, 'city_id');?>
        </div>
    </div>
    <div class="form-actions">
            <div class="row-fluid">
                    <?=$form->dropDownList($model, 'searchConditionType', ['AND' => 'Совпадают все поля', 'OR' => 'Должно совпасть одно из полей']);?>

            </div>
            <br>
            <div class="row-fluid">
                <?=CHtml::submitButton('Найти', ['name' => 'button_search', 'class' => 'btn btn-success']);?>
            </div>
    </div>
	<?php $this->endWidget(); ?>

protected/modules/clients/views/clients/form/update.php
<?php
    /* @var $model Clients */
    /* @var $form CActiveForm */
    /* @var $this Controller */

    if(is_null($model)) { echo 'Клиент не найден.'; return;}

    $model->setScenario($model->hasErrors() ? 'form_error' : 'edit');
    $model->validate(null, false);
    if( ! Yii::app()->request->isPostRequest) $model->clearErrors();
?>
<div style="padding: 20px 0 20px 0">
    <a href="/clients/clients/">Список клиентов</a> / <span>"<?php echo $model->title;?>"</span>
</div>
<?
    if( ! $model->isNewRecord) echo CHtml::link('Настройка рассылки', Yii::app()->createUrl('clients/subscriptions', ['clientId' => $model->id]), ['class' => 'btn btn-success']);
?>
<br>
<br>
<?php
    $regions = Regions::model()->findAll(new CDbCriteria(['condition' => 'parentId!=0', 'order' => 'title']));
    $branches = Branches::model()->findAll(new CDbCriteria(['order' => 'title']));
?>


<?php
    $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array( 'id' => 'clients', /*'enableAjaxValidation' => true*/));
    if( ! $model->isNewRecord) CHtml::hiddenField('id', $model->id);
    $form->errorSummary($model);
?>
<div class="row-fluid">
    <div class="span6">
        <? $this->renderPartial('form/update/company', ['model' => $model, 'form' => $form]); ?>
        <? $this->renderPartial('form/update/company_contacts', ['model' => $model, 'form' => $form]); ?>
    </div>
    <div class="span6">
        <? $this->renderPartial('form/update/detail_info', ['model' => $model, 'form' => $form]); ?>
    </div>
</div>

<div class="row-fluid">
    <? $this->renderPartial('form/update/sale', ['model' => $model, 'form' => $form]); ?>
</div>


<?=CHtml::submitButton('Сохранить', ['class' => 'btn btn-primary']);?>

<?php $this->endWidget(); ?>