protected/modules/clients/controllers/FilterController.php
<?php

/**
 * Контроллер фильтра клиентов
 */
class FilterController extends Controller
{

    /**
     * @return array action filters
     */
    public function filters()
    {
        return ['accessControl'];
    }

    public function accessRules()
    {
        return [
            [
                'allow',
                'roles' => ['manager'],
            ],
            [
                'deny', // deny all users
                'users' => ['*'],
            ],
        ];
    }

    /**
     * Отображение фильтра и результатов фильтрации.
     */
    public function actionIndex()
    {
        $this->title = 'Фильтр';
        $requestData = Yii::app()->request->getParam('Clients', []);
        $model = new Clients('search');
        // Убираем статус клиента "Лид" по умолчанию
        $model->client_status = null;
        $model->attributes = $requestData;
        # Менеджеры видят своих клиентов, "руководители отделов" - и своих клиентов и клиентов своих подчиненных
        if (!Yii::app()->user->checkAccess('admin')) {
            if (isset(Users::$usersRelations[Yii::app()->user->id])) {
                $model->dbCriteria->mergeWith(
                    [
                        'condition' => 'user_id IN (' . implode(',', Users::$usersRelations[Yii::app()->user->id]) . ')',
                    ]
                );
            } else {
                $model->user_id = Yii::app()->user->id;
            }
        }

        if (!isset($requestData['importance'])) {
            $model->importance = '';
        }

        # Формируем список столбцов таблицы
        $tableColumns = [];
        $selectedRows = Yii::app()->request->getParam('selected_rows', Yii::app()->session->get('selectedRows'));
        if (!empty($selectedRows)) {
            Yii::app()->session->add('selectedRows', $selectedRows);
            $tableColumns = $this->getTableColumns(explode(',', $selectedRows));
        }

        # Исключаем "обработанных" клиентов
        $dataProvider = $model->search('extended', $selectedRows);
        $dataProvider->getCriteria()->mergeWith(WebUser::getExcludedRecordsListCriteria());

        /* да, это не айс, но иначе totalItemCount, при фильтрации по активным рассылкам, содержит количество
        клиентов без учета фильррации по активным рассылкам */
        $dataProvider->setTotalItemCount(count($model->findAll($dataProvider->criteria)));

        $this->render(
            'index',
            [
                'dataProvider' => $dataProvider,
                'tableColumns' => $tableColumns,
            ]
        );
    }

    /**
     * Сохранение поля при inline-редактировании
     * @throws CHttpException
     */
    public function actionSaveField()
    {
        $name = Yii::app()->request->getParam('name');
        $value = Yii::app()->request->getParam('value');
        $pk = (int)Yii::app()->request->getParam('pk');

        $model = Clients::model()->findByPk($pk);
        if ($model == null) {
            throw new CHttpException(404, "Элемент #$pk не найден");
        }

        # конвертирует дату в unix timestamp.
        if (in_array($name, ['next_contact', 'contract_end_date'])) {
            $value = strtotime($value);
        }

        if (!$model->saveAttributes([$name => $value])) {
            throw new CHttpException(500, "Не удалось сохранить элемент #$pk");
        }
    }

    /**
     * Возвращает модель клиента по id
     * @param $id - идентификатор клиента
     * @return Clients
     * @throws CHttpException
     */
    protected function getModel($id)
    {
        $model = Clients::model()->findByPk($id);

        if ($model === null) {
            throw new CHttpException(404, "Модель #$id не найдена.");
        }

        return $model;
    }

    /**
     * Наполняет и сохраняет модель, полученную из запроса
     * @param $model Clients - модель клиента
     * @return bool
     * @throws CHttpException
     */
    protected function saveModelFromRequest(Clients $model)
    {
        $model->attributes = Yii::app()->request->getPost('Clients', []);
        if (!$model->save()) {
            throw new CHttpException(500, "Не удалось сохранить модель #{$model->id}}");
        }

        return true;
    }

    /**
     * При GET-запросе рендерит форму редактирования контактных лиц
     * При POST-запросе - сохраняет контактные лица и рендерит обновленное содержимое ячейки
     * @param $id - идентивикатор клиента
     */
    public function actionGetContactNameForm($id)
    {
        $model = $this->getModel($id);

        if (Yii::app()->request->isPostRequest) {
            $this->saveModelFromRequest($model);
            $content = Clients::getContactNameString($model);
            echo empty($content) ? 'нет данных' : $content;
            Yii::app()->end();
        }

        Yii::import('bootstrap.widgets.TbActiveForm');
        $form = $this->beginWidget(
            'TbActiveForm',
            ['id' => 'js-modal-form', 'htmlOptions' => ['style' => 'max-width: 600px']]
        );
        $this->renderPartial('/clients/form/update/contact_name_fields', ['form' => $form, 'model' => $model]);
        $this->endWidget();
    }

    /**
     * При GET-запросе рендерит форму редактирования адресов
     * При POST-запросе - сохраняет адреса и рендерит обновленное содержимое ячейки
     * @param $id - идентивикатор клиента
     */
    public function actionGetAddressForm($id)
    {
        $model = $this->getModel($id);

        if (Yii::app()->request->isPostRequest) {
            $this->saveModelFromRequest($model);
            $content = Clients::getAddressString($model);
            echo empty($content) ? 'нет данных' : $content;
            Yii::app()->end();
        }

        Yii::import('bootstrap.widgets.TbActiveForm');
        $form = $this->beginWidget(
            'TbActiveForm',
            ['id' => 'js-modal-form', 'htmlOptions' => ['style' => 'max-width: 600px']]
        );
        $this->renderPartial('/clients/form/update/address_fields', ['form' => $form, 'model' => $model]);
        $this->endWidget();
    }

    /**
     * При GET-запросе рендерит форму редактирования email
     * При POST-запросе - сохраняет email и рендерит обновленное содержимое ячейки
     * @param $id - идентивикатор клиента
     * @throws CHttpException
     */
    public function actionGetEmailForm($id)
    {
        $model = $this->getModel($id);

        if (Yii::app()->request->isPostRequest) {
            $model->setScenario('search');
            $model->attributes = Yii::app()->request->getPost('Clients', []);

            if (!Clients::saveEmailsString($model->id, $model->searchedEmails)) {
                throw new CHttpException(500, "Не удалось сохранить модель #$id");
            }

            $content = Clients::getEmailsString($model);
            echo empty($content) ? 'нет данных' : $content;
            Yii::app()->end();
        }

        Yii::import('bootstrap.widgets.TbActiveForm');
        $form = $this->beginWidget(
            'TbActiveForm',
            ['id' => 'js-modal-form', 'htmlOptions' => ['style' => 'max-width: 600px']]
        );
        echo $form->textField(
            $model,
            'searchedEmails',
            ['value' => Clients::getEmailsString($model), 'class' => 'span12']
        );
        $this->endWidget();
    }

    /**
     * При GET-запросе рендерит форму редактирования телефонов
     * При POST-запросе - сохраняет телефоны и рендерит обновленное содержимое ячейки
     * @param $id - идентивикатор клиента
     * @throws CHttpException
     */
    public function actionGetPhoneForm($id)
    {
        $model = $this->getModel($id);

        if (Yii::app()->request->isPostRequest) {
            $model->setScenario('search');
            $model->attributes = Yii::app()->request->getPost('Clients', []);

            if (!Clients::savePhonesString($model->id, $model->searchedPhones)) {
                throw new CHttpException(500, "Не удалось сохранить модель #$id");
            }

            $content = Clients::getPhonesString($model);
            echo empty($content) ? 'нет данных' : $content;
            Yii::app()->end();
        }

        Yii::import('bootstrap.widgets.TbActiveForm');
        /* @var $form TbActiveForm */
        $form = $this->beginWidget(
            'TbActiveForm',
            ['id' => 'js-modal-form', 'htmlOptions' => ['style' => 'max-width: 600px']]
        );
        echo $form->textField(
            $model,
            'searchedPhones',
            ['value' => Clients::getPhonesString($model), 'class' => 'span12']
        );
        $this->endWidget();
    }


    /**
     * При GET-запросе рендерит форму протокола общения с клиентом
     * При POST-запросе - рендерит обновленное содержимое ячейки
     * @param $id - идентивикатор клиента
     * @throws CHttpException
     */
    public function actionGetProtocolForm($id)
    {
        $model = Clients::model()->findByPk($id);

        if ($model === null) {
            throw new CHttpException(404, "Модель #$id не найдена.");
        }

        if (Yii::app()->request->isPostRequest) {
            $content = ClientProtocol::getLastItemsForSearchResultView($model->id);
            echo empty($content) ? 'нет данных' : $content;
            Yii::app()->end();
        }

        Yii::import('bootstrap.widgets.TbActiveForm');
        $this->beginWidget(
            'TbActiveForm',
            ['id' => 'js-modal-form', 'htmlOptions' => ['style' => 'max-width: 1100px']]
        );
        $this->renderPartial(
            '/clients/form/update/protocol_inline_form_fields',
            [
                'model' => $model,
                'limit' => 999
            ]
        );
        $this->endWidget();
    }

    /**
     * Добавляет клиента в список "обработанных" для текущего пользователя
     * @throws CHttpException
     */
    public function actionExcludeRecord()
    {
        $id = (int)Yii::app()->request->getPost('id');

protected/modules/clients/views/filter/form/_searchExtended_old.php
<?php
/* @var $form CActiveForm */
/* @var $this Controller */
/* @var $model Clients */
?>
<div class="form">
<?php
$form = $this->beginWidget('CActiveForm', array(
        'id' => 'clients',
        'method' => 'GET',
        'action' => $this->createUrl('filter/index'),
        /*'enableAjaxValidation' => true*/));?>
<table>
<? /* ===== Наименование клиента ===== */ ?>
<tr>
    <td style="width:250px;"><?=$form->labelEx($model, 'title'); ?></td>
    <td>
        <?=$form->textField($model, 'title', ['style' => 'width: 100%']);?>
        <?=$form->error($model, 'title'); ?>
    </td>
</tr>
<? /* ===== Телефон ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'searchedPhones'); ?></td>
    <td>
        <?=$form->textField($model, 'searchedPhones', ['style' => 'width: 100%']);?>
        <?=$form->error($model, 'searchedPhones'); ?>
    </td>
</tr>
<? /* ===== Email ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'searchedEmails'); ?></td>
    <td>
        <?=$form->textField($model, 'searchedEmails', ['style' => 'width: 100%']);?>
        <?=$form->error($model, 'searchedEmails'); ?>
    </td>
</tr>

<? /* ===== Контактное лицо 1 ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'contact_name1'); ?></td>
    <td>
        <?=$form->textField($model, 'contact_name1', ['style' => 'width: 100%']);?>
        <?=$form->error($model, 'contact_name1'); ?>
    </td>
</tr>

<? /* ===== Контактное лицо 2 ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'contact_name2'); ?></td>
    <td>
        <?=$form->textField($model, 'contact_name2', ['style' => 'width: 100%']);?>
        <?=$form->error($model, 'contact_name2'); ?>
    </td>
</tr>

<? /* ===== Контактное лицо 3 ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'contact_name3'); ?></td>
    <td>
        <?=$form->textField($model, 'contact_name3', ['style' => 'width: 100%']);?>
        <?=$form->error($model, 'contact_name3'); ?>
    </td>
</tr>

<? /* ===== Менеджер ===== */ ?>
<? if(Yii::app()->user->checkAccess('admin')) { ?>
    <tr>
        <td><?=$form->labelEx($model, 'user'); ?></td>
        <td>
            <?=$form->dropDownList($model, 'user_id', CMap::mergeArray(['' => '--- любой ---'], CHtml::listData(Users::model()->findAll(), 'userId', 'name')), ['style' => 'width: 100%']);?>
            <?=$form->error($model, 'user'); ?>
        </td>
    </tr>
<?}?>

<? /* ===== Отрасль ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'branch'); ?></td>
    <td>
        <?=$form->dropDownList($model, 'branch_id', CMap::mergeArray(['' => '--- любая ---'], CHtml::listData(Branches::model()->findAll(), 'branchId', 'title')), ['style' => 'width: 100%']);?>
        <?=$form->error($model, 'branch'); ?>
    </td>
</tr>

<? /* ===== Род деятельности ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'career'); ?></td>
    <td>
        <?=$form->textField($model, 'career', ['style' => 'width: 100%']);?>
        <?=$form->error($model, 'career'); ?>
    </td>
</tr>

<? /* ===== Сайт ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'website'); ?></td>
    <td>
        <?=$form->textField($model, 'website', ['style' => 'width: 100%']);?>
        <?=$form->error($model, 'website'); ?>
    </td>
</tr>

<? /* ===== Регион ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'region'); ?></td>
    <td>
        <?php
        echo $form->hiddenField($model, 'region_id');
        $this->widget('zii.widgets.jui.CJuiAutoComplete', [
                'name' => 'region_title',
                'value' => $model->region ? $model->region->OFFNAME.' '.$model->region->SHORTNAME : '',
                'source' => 'js: function(request, response) {
					$.ajax({
						url: "/clients/clients/getRegions/",
						dataType: "json",
						beforeSend: function() { $("#loading_regions").show(); },
						complete: function() { $("#loading_regions").hide(); },
						data: { title: request.term },
						success: function(data) {
							response(data
								? $.map(data, function(item) {
									var title = item.title + " " + item.short_name;

									return { id: item.id, value: title, label: title, region_id: item.region_id };
								})
								: {}
							);
						}
					});
				}',
                // additional javascript options for the autocomplete plugin
                'options' => [
                    'showAnim' => 'fold',
                    'select'   => 'js: function(event, ui) {
						$("#'.get_class($model).'_region_id").val(ui.item.id);
						$("#city_region").val(ui.item.region_id);
						$("#'.get_class($model).'_city_id").val("");
						$("#city_title").val("");
					}',
                    'change'   => 'js: function(event, ui) {
						if (!ui.item) {
							$("#'.get_class($model).'_region_id").val("");
							$("#city_region").val("");
						}

						$("#'.get_class($model).'_city_id").val("");
						$("#city_title").val("");
					}'
                ],
                'htmlOptions' => [
                    'style' => 'width: 100%'
                ],
            ]);
        ?>
        <img id="loading_regions" style="display: none;" src="<?=Yii::app()->request->baseUrl;?>/images/spinner.gif" />
        <?=$form->error($model, 'region_id'); ?>
    </td>
</tr>


<? /* ===== Адрес ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'address'); ?></td>
    <td>
        <?=$form->textField($model, 'address', ['style' => 'width: 100%']);?>
        <?=$form->error($model, 'address'); ?>
    </td>
</tr>

<? /* ===== Юридический адрес ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'legal_address'); ?></td>
    <td>
        <?=$form->textField($model, 'legal_address', ['style' => 'width: 100%']);?>
        <?=$form->error($model, 'legal_address'); ?>
    </td>
</tr>

<? /* ===== Город ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'city'); ?></td>
    <td>
        <?php
        echo CHtml::hiddenField('city_region', $model->region ? $model->region->AOGUID : '', ['id' => 'city_region']);
        echo $form->hiddenField($model, 'city_id');
        $this->widget('zii.widgets.jui.CJuiAutoComplete', [
                'name' => 'city_title',
                'value' => $model->city ? $model->city->OFFNAME.' '.$model->city->SHORTNAME : '',
                'source' => 'js: function(request, response) {
					$.ajax({
						url: "/clients/clients/getCities/",
						dataType: "json",
						beforeSend: function() { $("#loading_cities").show(); },
						complete: function() { $("#loading_cities").hide(); },
						data: { region: $("#city_region").val(), title: request.term },
						success: function(data) {
							response(data
								? $.map(data, function(item) {
									var title = item.title + " " + item.short_name,
										label = title + " (" + item.region_title + " " + item.region_short_name + ")";

									return { id: item.id, value: title, label: label }
								})
								: {}
							);
						}
					});
				}',
                // additional javascript options for the autocomplete plugin
                'options' => [
                    'showAnim' => 'fold',
                    'select'   => 'js: function(event, ui) {
						$("#'.get_class($model).'_city_id").val(ui.item.id);
					}',
                    'change'   => 'js: function(event, ui) {
						if (!ui.item) {
							$("#'.get_class($model).'_city_id").val("");
						}
					}'
                ],
                'htmlOptions' => [
                    'style' => 'width: 100%'
                ],
            ]);
        ?>
        <img id="loading_cities" style="display: none;" src="<?=Yii::app()->request->baseUrl;?>/images/spinner.gif" />
        <?=$form->error($model, 'city_id'); ?>
    </td>
</tr>

<? /* ===== ИНН ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'inn'); ?></td>
    <td>
        <?=$form->textField($model, 'inn', ['style' => 'width: 100%']);?>
        <?=$form->error($model, 'inn'); ?>
    </td>
</tr>

<? /* ===== КПП ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'kpp'); ?></td>
    <td>
        <?=$form->textField($model, 'kpp', ['style' => 'width: 100%']);?>
        <?=$form->error($model, 'kpp'); ?>
    </td>
</tr>

<? /* ===== Дата окончания контракта ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'contract_end_date'); ?></td>
    <td>
        <?=$form->dateField($model, 'contract_end_date');?>
        <?=$form->error($model, 'contract_end_date'); ?>
    </td>
</tr>

<? /* ===== Дата следующего контакта ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'next_contact'); ?></td>
    <td>
        <?=$form->dateField($model, 'next_contact');?>
        <?=$form->error($model, 'next_contact'); ?>
    </td>
</tr>

<? /* ===== Уровень важности ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'importance'); ?></td>
    <td>
        <?=$form->dropDownList($model, 'importance',
            [
                '' => '--- любой ---',
                'Минимальная важность' => 'Минимальная важность',
                'Высокая важность' => 'Высокая важность',
                'Край географии' => 'Край географии',
            ], ['style' => 'width: 100%']);?>
        <?=$form->error($model, 'importance'); ?>
    </td>
</tr>

<? /* ===== Дата последней записи в протоколе ===== */ ?>
<tr>
    <td><?=$form->labelEx($model, 'searchedLastProtocolRecordDate'); ?></td>
    <td>
        <?=$form->dateField($model, 'searchedLastProtocolRecordDate');?>
        <?=$form->error($model, 'searchedLastProtocolRecordDate'); ?>
    </td>
</tr>

<?/* ===== Тип поиска ===== */ ?>
<tr>
    <td>&nbsp;</td>
    <td>
        <?= $form->dropDownList($model, 'searchConditionType', ['AND' => 'Совпадают все поля', 'OR' => 'Должно совпасть одно из полей',])?>
        <?= CHtml::tag('br')?>
        <?= CHtml::submitButton('Найти', ['name' => 'button_search']);?>
    </td>
</tr>

</table>
<?php $this->endWidget(); ?>
</div>

protected/modules/clients/views/filter/form/selectebleSearchExtended.php
<?php
/* @var Controller $this */

Yii::app()->clientScript->registerScriptFile(
    Yii::app()->assetManager->publish(
        Yii::getPathOfAlias('application.modules.clients.assets.js.clients_filter') . '.js'
    )
);

Yii::import('bootstrap.widgets.TbActiveForm');
$form = new TbActiveForm();
?>
<form>
    <? echo CHtml::tag(
        'input',
        [
            'id' => 'js-selected-rows-names',
            'name' => 'selected_rows',
            'type' => 'hidden',
            'value' => Yii::app()->session->get('selectedRows')
        ]
    ); ?>
    <div class="row-fluid">
        <?= CHtml::button(
            'Скрыть/показать фильтр',
            ['class' => 'btn btn-success', 'onclick' => '$("#js-filter-area").toggle();']
        ) ?>
        <br><br>
    </div>
    <div id="js-filter-area">
        <div class="row-fluid">
            <div id='js-available-filter-fields' class="span4">

                <div class="well well-small">Фильтры</div>
                <?php
                foreach (Clients::getFilterFieldNames() as $fieldName) {
                    # не выводим поле менеджер для простых пользователей
                    if ($fieldName == 'user_id') {
                        $usersList = Users::getDropdownList(Yii::app()->user);
                        if (empty($usersList)) {
                            continue;
                        }
                    }
                    ?>
                    <label class="checkbox" for="<?= $fieldName ?>">
                        <input id="<?= $fieldName ?>" type="checkbox"/>
                        <?= $model->getAttributeLabel($fieldName); ?>
                    </label>
                <?php
                }
                ?>
            </div>

            <div id='js-actual-filter' class="span8">
                <div class="well well-small">Значения</div>
                <? $this->renderPartial('form/rowPrototypes', ['form' => $form, 'model' => $model]) ?>
            </div>
        </div>
        <div class="row-fluid">
            <?= CHtml::submitButton('Найти', ['class' => 'btn btn-primary', 'name' => 'search_button']); ?>
        </div>
    </div>

</form>